package com.example.weatherapp.model;

import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;
import lombok.Data;


@Data // Lombok annotation to generate getters, setters, toString, etc.
@Document(collection = "users") // Specifies the collection name in MongoDB
public class User {

    @Id
    private String id; // Will be automatically generated by MongoDB

    private String username;
    private String email;
    private String password; // In a real app, this should be securely hashed

    private WeatherPreferences preferences = new WeatherPreferences(); // Embeds the preferences
}
